name: iptv-restream

services:
  iptv_restream_frontend:
    image: "${IMAGE_REGISTRY:-ghcr.io/miduncan/iptv-restream}/frontend:${IMAGE_TAG:-latest}"
    restart: unless-stopped
    networks:
      - app-network

  iptv_restream_backend:
    image: "${IMAGE_REGISTRY:-ghcr.io/miduncan/iptv-restream}/backend:${IMAGE_TAG:-latest}"
    volumes:
      - streams_data:/streams
      - channels:/channels
    restart: unless-stopped
    environment:
      STORAGE_PATH: /streams/
      AUTH_VIEWER_USERNAME: "${AUTH_VIEWER_USERNAME:-}"
      AUTH_VIEWER_PASSWORD: "${AUTH_VIEWER_PASSWORD:-}"
      AUTH_ADMIN_USERNAME: "${AUTH_ADMIN_USERNAME:-}"
      AUTH_ADMIN_PASSWORD: "${AUTH_ADMIN_PASSWORD:-}"
      # If you have problems with the playlist, set the backend url manually here
      #BACKEND_URL: http://localhost:5000
    networks:
      - app-network

  # Nginx Reverse Proxy
  iptv_restream_nginx:
    image: "${IMAGE_REGISTRY:-ghcr.io/miduncan/iptv-restream}/nginx:${IMAGE_TAG:-latest}"
    restart: unless-stopped
    volumes:
      - streams_data:/streams
    ports:
      - "80:80" # Configure exposed port, if 80 is already in use e.g. 8080:80
    networks:
      - app-network

volumes:
  streams_data:
    driver: local
    driver_opts:
      type: tmpfs
      device: tmpfs
  channels:

# Internal docker network
networks:
  app-network:
    driver: bridge
